# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CallbagExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Callbag',  :path => '../Callbag/'
  pod 'CallbagCocoa', :path => '../CallbagCocoa/'
  # Pods for CallbagExample

  target 'CallbagExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
